# Generated by Django 4.2.3 on 2023-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='office',
            name='country',
            field=models.CharField(default='England', max_length=100),
            preserve_default=False,
        ),
    ]
